[package]
name = "capnp_rpc_example"
version = "0.1.0"
edition = "2024"

[dependencies]
capnp = "0.21.0"
capnp-rpc = "0.21.0"
futures = "0.3.31"
tokio = {version= "1.44.2", features = ["full"]}
tokio-util = {version= "0.7.0", features = ["compat"]}

[build-dependencies]
capnpc = "0.21.0"
